### ISSUE TITLE
"Download Results" link is broken

### ISSUE THREAD

**Issue by wesleycrouse** [astheeggeggs/UKBB_ldsc_r2#3]
I am unable to download the UK Biobank genetic correlation results available via the "Download Results" link located here: [https://ukbb-rg.hail.is/](https://ukbb-rg.hail.is/). When I try to access the link, I receive an error from Dropbox. If there is an alternate location to access these results or this issue can be resolved, please let me know. Thank you in advance.

**Comment by pjordab** [comment]
Hi,
First of all, many thanks for creating and sharing this tool.
I'm having the same issue posted by this user and it also disconnects me from the server when I search through the browser.
Any idea of what is going on?
Many thanks!

**Comment by astheeggeggs** [comment]
Hi both, thanks for using the browser, and apologies for not spotting this sooner. I have contacted the hosts of the website with an updated link. In the meantime here's a google drive link to all the results: https://drive.google.com/file/d/1PgPEj4uG6v4DcuxBEbnAu8DXuPaQbA-k/view?usp=sharing. As for why it's dropping you off the server, I'm not sure why that's happening. Are you still having issues?

**Comment by wesleycrouse** [comment]
The link works again. Thank you!
