### ISSUE TITLE
Citation to the UKBB Genetic Correlation website

### ISSUE THREAD

**Issue by Jesson-mark** [astheeggeggs/UKBB_ldsc_r2#4]
Hi, 
thanks for your great contributions to the genetic correlations of UKBB phenotypes! 
My work was inspired by the results of the genetic correlations websites and I want to cite it. 
Is there any publication related to the UKBB genetic correlations? 

Best regards， 
Jie Wang

**Comment by astheeggeggs** [comment]
Hi Jie Wang,

Great that you've found it useful! There's no publication related to the correlations, but I've just created a zenodo doi for the github repo ([DOI: 10.5281/zenodo.10691025](https://doi.org/10.5281/zenodo.10691025)), and you're more than welcome to cite the website if you found that aspect useful too.

All the best,
Duncan

**Comment by Jesson-mark** [comment]
Thanks for your promp reply! I will choose a way to cite this! 

Best regards, 
Jie Wang
